### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by vzaliva** [ballercat/minimal-webpack5-wasm-demo#2]
```
yarn run v1.22.22
$ /home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/.bin/webpack serve
node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next29 (eval at create (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:36:1)
    at _next7 (eval at create (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:115:1)
    at Hook.CALL_DELEGATE [as _call] (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/lord/tmp/minimal-webpack5-wasm-demo/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 !  ~/t/minimal-webpack5-wasm-demo   main  git remote
origin
 ~/t/minimal-webpack5-wasm-demo   main  git remote -v
origin  git@github.com:ballercat/minimal-webpack5-wasm-demo.git (fetch)
origin  git@github.com:ballercat/minimal-webpack5-wasm-demo.git (push)
 ~/t/minimal-webpack5-wasm-demo   main 
 ```

**Comment by vzaliva** [comment]
Workaround:

`export NODE_OPTIONS=--openssl-legacy-provider`
